matrix:
  include:
    # - language: node_js
    #   cache: npm
    #   node_js:
    #     - "8"
    #   script:
    #     # React/Node tests
    #     - cd AutoRpg.Web/ClientApp
    #     - npm install
    #     - npm test
    - language: csharp
      solution: AutoRpg.sln
      mono: none
      dotnet: 2.1.300
      script:
        # .NET Core tests
        #- dotnet test AutoRpg.Web.Tests/AutoRpg.Web.Tests.csproj
        #- dotnet test AutoRpg.Authentication.Tests/AutoRpg.Authentication.Tests.csproj
        dotnet build AutoRpg.sln